### ISSUE TITLE
Question abort the paper "Columnar Storage and List-based Processing for Graph Database Management Systems"

### ISSUE THREAD

**Issue by ysj1173886760** [kuzudb/kuzu#1078]
Hi, i found that you guys has made kuzu open sourced recently, and columnar storage module of kuzu attracted me a lot.
I've followed the reference in your newest paper and found the paper(Columnar Storage and List-based Processing for Graph Database Management Systems) described your design of columnar storage.
In Section 1 Paragraph 2, you have stated that:
> Despite their similarities, workloads in GDBMSs and columnar RDBMSs also have fundamentally different access patterns. For example, workloads in GDBMSs contain large manyto-many joins, which are not frequent in column-oriented RDBMSs.

I want to ask 3 question:
1. what is many-to-many join? does that means k-hop query?
2. why does GDBMS contains large many-to-many join that RDBMS?
3. in these many-to-many join scenarios, how can GDBMS perform better than RDBMS?

These questions might be kind of high-level, so i want to ask some professional opinions like you guys and wang to gain some intuition.

**Comment by semihsalihoglu-uw** [comment]
Hi,

Let me provide some short answers here. 

For 1: m-n joins refers to the fact that one record in your db may join with multiple records when evaluating your queries. Therefore these joins are growing in size (often beyond the original number of your records). A join being m-n is a property of the underlying datasets and "the join". Joins are joins: they are a core relational operation.

For 2: Let me clarify this. Any DBMS that implements a high-level language and supports joins, can evaluate m-n joins. If this is coming from a paper or talk from my group, we must have said that the applications that GDBMSs frequently support, e.g., fraud detection or recommendations (among many other applications) often have m-n relationships between node records, so joins are m-n.

For 3: It's difficult to say something universal about GDBMSs, but Kùzu implements many techniques/optimizations to do these joins very well, such as factorization, our novel ASPJoin operator (more details can be found in the code or our CIDR 2023 paper),   or worst-case optimal join algorithms. Perhaps one thing that is close-to-universal in GDBMSs for joins is GDBMSs generally have a join index that indexes the system-level dense integer-based IDs of node records that join with each other. In graph jargon, this is called the "adjacency list index" as it indexes for each node record u, u's "neighbors". In DBMS literature, this is a specific implementation of what we call a join index. Believe it or not, this is something first introduced in 1987 but not widely adopted in RDBMSs. They make joins faster because all joins become dense integer based and if few (node) records are being joined (e.g., only one node representing "Alice"), the index is very efficient and avoids a full scan/join of your (node) records.

Hope this helps.

**Comment by ysj1173886760** [comment]
Much appreciate!
I found your works surprisingly fascinating and was trying to understand the source code of kuzu.
Looking forward to contribute to kuzu someday.
