### ISSUE TITLE
Question: securing queries 

### ISSUE THREAD

**Issue by lmeyerov** [kuzudb/kuzu#1288]
We would like to restrict some queries to read only on a given dataset, and ideally, with limited compute time (# cores, # s, ...). We are looking at the python API via the parquet loader then running ~match queries, where the match should be limited to some files / namespace. Curious to thoughts here?

**Comment by andyfengHKU** [comment]
- In order to limit # cores/threads, you can use `set_max_threads_for_exec` in our Python API under [connection](https://kuzudb.com/docs/client-apis/python-api/connection.html).
- To limit # seconds, if my understanding is correct, you are asking for a timeout mechanism in database which we haven't planned such a feature. A possible alternative is to time at the application level. 
- For limiting match to some files / namespace, currently we don't support multiple databases. So the best practice might be creating multiple database directory each of which contains the set of files you want to query against.

Let us know if you have further questions. We are happy to provide support if you encounter problems with your use case.

**Comment by lmeyerov** [comment]
Thanks!

Yes, so looks like enforcing process timeouts is the only unknown for basic CIA security triad wrt having doable workarounds

**Comment by andyfengHKU** [comment]
Hi @lmeyerov, we recently introduced timeout mechanism in our release v0.0.3

**Comment by lmeyerov** [comment]
Interesting, thanks!
