### ISSUE TITLE
Failed to install through PIP(Python) in the windows.

### ISSUE THREAD

**Issue by yangkangnevergiveup** [kuzudb/kuzu#1311]
pip3 --no-cache-dir  install kuzu 

Collecting kuzu
  Downloading kuzu-0.0.2.zip (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 19.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/34/4d/64e1bcb741fbae199c4a2162204179625c04c405e8215bc819628751b4d5/kuzu-0.0.2.zip (from https://pypi.org/simple/kuzu/): Requested kuzu from https://files.pythonhosted.org/packages/34/4d/64e1bcb741fbae199c4a2162204179625c04c405e8215bc819628751b4d5/kuzu-0.0.2.zip has inconsistent version: filename has '0.0.2', but metadata has '0.0.1'
ERROR: Could not find a version that satisfies the requirement kuzu (from versions: 0.0.2)
ERROR: No matching distribution found for kuzu

**Comment by mewim** [comment]
Hi @yangkangnevergiveup. Thanks for reporting this. It seems that our source distribution metadata has a minor error, which causes the source distribution not to work. We will fix it in the next upload. This does not seem to affect the pre-compiled wheels though.

Aside from this issue, Kùzu also does not support Windows platform currently, which is the reason that we do not upload pre-compiled wheels for Windows and `pip` tries to build from source. Since we have not tested the system on Windows, we cannot guarantee that Kùzu will compile and work correctly on Windows unfortunately. If you are using Windows 10 / 11, we would encourage you to install and use Kùzu with [Linux subsystem](https://learn.microsoft.com/windows/wsl/install).

**Comment by yangkangnevergiveup** [comment]
Thank you for response. Yes, I tried to use KUZU on Windows and packaged my app with KUZU. KUZU is fine on MacOS/Linux. Too bad I cannot use KUZU on Windows. Expect KUZU to support Windows.

**Comment by yangkangnevergiveup** [comment]
@mewim Thank you for response. Yes, I tried to use KUZU on Windows and packaged my app with KUZU. KUZU is fine on MacOS/Linux. Too bad I cannot use KUZU on Windows. Expect KUZU to support Windows.

**Comment by semihsalihoglu-uw** [comment]
Hi @yangkangnevergiveup : We just made a release today that adds windows support. Please let us know if you try it and it does or does not work!
