### ISSUE TITLE
potential version error? pip install kuzu doesn't work with version 0.0.2

### ISSUE THREAD

**Issue by Abida2024** [kuzudb/kuzu#1313]
Here is the following error I receive when I run "pip install kuzu" 

Requested kuzu from https://files.pythonhosted.org/packages/34/4d/64e1bcb741fbae199c4a2162204179625c04c405e8215bc819628751b4d5/kuzu-0.0.2.zip has inconsistent version: expected '0.0.2', but metadata has '0.0.1'

ERROR: Could not find a version that satisfies the requirement kuzu (from versions: 0.0.2)
ERROR: No matching distribution found for kuzu

**Comment by mewim** [comment]
Hi @Abida2024. It seems that our source distribution metadata has a minor error, which causes the source distribution not to work. We will fix it in the next upload. This does not seem to affect the pre-compiled wheels though.

Also, it seems that you are installing from a platform that we do not support, which is the reason that we do not have a pre-compiled wheel and pip tries to build from source. Could you please let us know which platform you are installing on?

**Comment by Abida2024** [comment]
Thanks for the super quick response, I'm installing on windows 11?

**Comment by mewim** [comment]
Hi @Abida2024, unfortunately Kùzu does not support Windows platform currently, which is the reason that we do not upload pre-compiled wheels for Windows and pip tries to build from source. Since we have not tested on Windows, we cannot guarantee that Kùzu will compile and work correctly on Windows. If you are using Windows 10 / 11, we would encourage you to install and use Kùzu with [Linux subsystem](https://learn.microsoft.com/windows/wsl/install).

**Comment by Abida2024** [comment]
I see, thank you so much for your help!

**Comment by semihsalihoglu-uw** [comment]
Hi @Abida2024:  We just made a release today that adds windows support. Please let us know if you try it and it does or does not work!
