### ISSUE TITLE
CSV file: String value NA not imported

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1323]
I tried to load some CSV data into a node table. The CSV file was very simple and contains a single column with 2-letter country codes, no header and the values are NOT quoted.

CSV sample:
MY

MZ

NA

NC

NE

The data was correctly imported except for the value: NA

` kuzu> create node table Country(code string, primary key(code));
kuzu> copy Country from "data/countries-test.csv";
---------------------------------------------------------
| 5 number of tuples has been copied to table: Country. |
---------------------------------------------------------
`

 Result:

` kuzu> match(c:Country) return c.code;
----------
| c.code |
----------
| MY     |
----------
| MZ     |
----------
|        |
----------
| NC     |
----------
| NE     |
----------
(5 tuples)
Time: 9.82ms (compiling), 0.59ms (executing)
`

I assume that NA is interpreted as "not available" respectively null. If the String is quoted then the value is correctly imported.

Uwe

**Comment by ray6080** [comment]
Hi @uwegeercken , thanks for reporting this! Yes, you're right, the reason behind this "bug" is because NA is not correctly interpreted as a non-null string value. We currently use [arrow](https://arrow.apache.org/)'s CSV reader, and by default configures it to allow a set of "null_values" (including NA) interpreted as NULLs for strings. We're changing this soon, and will update you here soon as it's done.
Thanks!
