### ISSUE TITLE
Test performance drops quickly after running LSQB test

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1651]
I notice that before LSQB test, our average test cases takes around 0.15s. While after running LSQB test, all subsequent test cases take longer, average 0.6s on my machine. I wonder if this is because LSQB test bump BM size up and we don't reset BM size to a smaller size afterwards?

**Comment by rfdavid** [comment]
Update:

`ctest` command calls the binary `e2e_test` for each test. We currently have 222 tests, so for each test ctest runs somethling like:

```
Test command: /Users/rfdavid/Devel/waterloo/kuzu/build/release/test/runner/e2e_test "--gtest_filter=BinderErrorTest.AddPropertyDuplicateName" "--gtest_also_run_disabled_tests"
```

`e2e_test` recursively scans test_files directory, parses all `.test` files, convert to parquet the necessary CSV, registers all the tests, and then it executes only the test passed in the argument. This is executed 222 times, but only now we noticed the performance due to the csv -> parquet conversion.
