### ISSUE TITLE
Memory sanitizer error report

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1825]
The memory sanitizer check on CI is reporting a memory leak and SEG fault error on CAPI test.

**Comment by benjaminwinger** [comment]
I was looking at this after seeing this failing, and while I'm not sure about the other tests, the `Interrupt` C API test it looks to me like it's both possible for the thread used by the test to try to interrupt a connection that's been destroyed since it gets detached and won't be joined when it goes out of scope, and also looks like the interrupt function will set the interrupted flag even when the activeQuery is null.
