### ISSUE TITLE
RuntimeError: Binder exception: Cannot store a fixed list of size 4816 in a page.

### ISSUE THREAD

**Issue by satoshi-iwata** [kuzudb/kuzu#1912]
Hi.

I tried to create a table for storing this data with a Python script.
https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.Reddit.html#torch_geometric.datasets.Reddit

```
conn.execute(
    "CREATE NODE TABLE post(id INT64, x DOUBLE[602], train_mask INT32, y INT32, "
    "PRIMARY KEY (id));")
```

And an error occurred.
```
RuntimeError: Binder exception: Cannot store a fixed list of size 4816 in a page.
```

Is it a known issue? Are there any ways to avoid the error?

**Comment by mewim** [comment]
Hi @satoshi-iwata,

This is a known issue. Currently the size of a list is limited one page, which 4096 bytes. We are actively working on a new version of the storage, which will lift this restriction. For storing the Reddit dataset, you can using `FLOAT` instead of `DOUBLE`, which takes 4 bytes per element instead of 8, so the feature vector should fit into one page.

**Comment by satoshi-iwata** [comment]
Hi @mewim,

Understood. Thanks for your quick response!
