### ISSUE TITLE
Rust API test_arrow test fails due to Utf8Error on macos-11 GitHub-hosted runner

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2005]
The test has failed 2 out of 2 times so far.
Logs and workflow files can be found here:
https://github.com/kuzudb/kuzu/actions/runs/6111754214/job/16587694174
https://github.com/kuzudb/kuzu/actions/runs/6113068279/job/16591808577

**Comment by russell-liu** [comment]
I think I've figured out why it is failing -- the macos-11 runner uses Clang/LLVM 13.0.0 by default (https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md), whereas we inexplicitly require 14. This is demonstrated by these two runs, one of which failed and one of which succeeded, which differ only by Clang/LLVM version:
https://github.com/kuzudb/kuzu/actions/runs/6122821358/job/16619417254
https://github.com/kuzudb/kuzu/actions/runs/6122418640/job/16618126207

**Comment by russell-liu** [comment]
Never mind, it can also fail with Clang/LLVM 14:
https://github.com/kuzudb/kuzu/actions/runs/6122975487/job/16619878211

**Comment by benjaminwinger** [comment]
As some context for the error, it's being raised by [this line in arrow-rs](https://github.com/apache/arrow-rs/blob/878217b9e330b4f1ed13e798a214ea11fbeb2bbb/arrow-schema/src/ffi.rs#L254), where it's accessing the name field of the schema. 

That name field should either be what's set [here](https://github.com/kuzudb/kuzu/blob/master/src/common/arrow/arrow_converter.cpp#L128) as a hardcoded ascii string, or one of the property names as set [here](https://github.com/kuzudb/kuzu/blob/d03d306f6c8063f380921ae7708d4014eca81f47/src/common/arrow/arrow_converter.cpp#L24) (the rust test failing has a string column called `name` and an int64 column called `age`).

I think the problem is that the property names are owned by the `DataTypeInfo` struct, rather than being moved into the ArrowSchema like the rest of the information, and the DataTypeInfo used in getArrowSchema is temporary. Struct field names are moved into the ArrowSchemaHolder, but property names are not.

We should also add a tests of `getArrowSchema` and `getNextArrowChunk`, as issues like this could be caught by the address sanitizer (it may not be needed for the rust code, but it is needed for C++ interfaces used by the rust code).

**Comment by russell-liu** [comment]
It also happens on Windows as well:
https://github.com/kuzudb/kuzu/actions/runs/6189154608/job/16802666644

**Comment by benjaminwinger** [comment]
Yes, it can occur on all platforms, but I think the last time you updated the branch you're testing on was the commit before #2019 was merged.

**Comment by russell-liu** [comment]
Oops, I had this page open and forgot to refresh it, so I wasn't aware that it has been fixed. Please ignore my previous comment.
