### ISSUE TITLE
C++ Example build fails due to cannot open file 'kuzu.lib' error on Windows

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2018]
Example failed run on windows-2022 GitHub-hosted runner -- logs and workflow file:
https://github.com/kuzudb/kuzu/actions/runs/6147199143/job/16678123825
There does not seem to be any evidence of this build ever succeeding on a Windows machine.

Edit:
Example failed run on windows-2019 GitHub-hosted runner -- logs and workflow file:
https://github.com/kuzudb/kuzu/actions/runs/6164811518/job/16731340752

Edit 2: On windows-2019, the error is different. It seems more similar to the C Example error in #2017.

Edit 3:
On windows-2022, something more similar to the C Example error in #2017 can also happen instead:
https://github.com/kuzudb/kuzu/actions/runs/6252947054/job/16977313652#step:10:1472

**Comment by benjaminwinger** [comment]
The CMakeLists for the C and C++ examples make assumptions about the structure of the CMake build directory for the main build which don't hold up on windows. CMake produces build artifacts within an `Out` directory if I remember correctly.

I think we should probably just add the examples as optional features of the main build so that they can be linked properly.

Eventually, if we want them to also serve as an example of how to link against kuzu using a cmake project, then we could have the main build install into a particular directory and pass that to the example builds, but that would be a lot more work to set up.

**Comment by russell-liu** [comment]
Fixed
