### ISSUE TITLE
python get_as_arrow api error

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2037]
When calling get_as_arrow api on the query result, the following error message is thrown:
/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/cpp/src/arrow/c/helpers.h:64:: ArrowSchemaRelease did not cleanup release callback[1]

**Comment by benjaminwinger** [comment]
Was this with or without #2019? Before that change the schema release function was broken and was always leaking data.

**Comment by acquamarin** [comment]
Just double checked the leak still exists on master.

**Comment by benjaminwinger** [comment]
Ok. I think the problem is probably with my workaround to avoid creating a new schema for each record batch ([here](https://github.com/kuzudb/kuzu/blob/314934ab34f652c0bdf784722b9fd46fb69db589/tools/python_api/src_cpp/py_query_result.cpp#L222C49-L231)). As far as I could tell it wasn't keeping any of the schema data, but I could have been mistaken (and that does explain why it was releasing it in the first place).

Do you know a way of reproducing the error? It's not showing up in our tests.
