### ISSUE TITLE
Possible Bug in Variable-length Query or Python API not handling UTF-8 correctly.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2268]
Code to reproduce
```
import kuzu
db = kuzu.Database('./test')
conn = kuzu.Connection(db)
conn.execute('''CREATE NODE TABLE Entity (
   id STRING,
   entity_type STRING,
   platform_type STRING,
   platform_id STRING,
   PRIMARY KEY (id)
);''')
conn.execute('''
CREATE REL TABLE Connection (
   FROM Entity TO Entity,
   connection_type STRING,
   platform_id STRING,
   job_id STRING,
   job_step_id STRING,
   created_time INT64
);
''')
conn.execute(
    '''
    copy Entity from "/Users/z473chen/Downloads/entities.parquet"
    '''
)
conn.execute(
    '''
    copy Connection from "/Users/z473chen/Downloads/connections.parquet"
    '''
)
result = conn.execute(
    '''
    MATCH p = (a:Entity)-[e:Connection*8..9]->(b:Entity) WHERE (a.id = 
    'openx|bigquery_prod|COLUMN|ox-data-prod.events.transactions_prompt_v3.arc.x_mkt_excluded' OR a.id = 
    'openx|bigquery_prod|TABLE|ox-data-prod.events.transactions_prompt_v3') WITH a.id AS a_id, p as path RETURN path 
    '''
)

while result.has_next():
    print(result.get_next())
```
pybind11 throws a utf-8 conversion exception, while c++ api/shell correctly returns the result.

One possible reason is that:
```
case LogicalTypeID::STRING: {
    return py::cast(value.getValue<std::string>());
}
```
This conversion code in pybind11 doesn't handle utf-8 well (maybe incorrect encoding is chosen).

**Comment by mewim** [comment]
It looks like that Python API can actually handle UTF-8 correctly:
```
>>> import kuzu
>>> db = kuzu.Database("test")
>>> conn = kuzu.Connection(db)
>>> conn.execute("RETURN '你好🍕'").get_next()
['你好🍕']
```

Also, I checked the parquet files and it looks like there is no UTF-8 character in the file. This may not be a UTF-8 conversion issue, but rather wrong data got fed into Python.

**Comment by mewim** [comment]
I added a print statement before https://github.com/kuzudb/kuzu/blob/ece824f27f835168b36e6c6ced8fdf989d0291e3/tools/python_api/src_cpp/py_query_result.cpp#L119 to print each string that got processed and it seems the strings that caused the problems is `?1m
bigq?L??prec?L?1a84449b3965??S??m`. This does not look like a valid value. 

The shell does not print the full output, so the result appeared to be correct, but I created a C++ program which opens the same database (by replacing the example):
```cpp
#include <iostream>

#include "main/kuzu.h"
using namespace kuzu::main;

int main() {
    auto database = std::make_unique<Database>("/Users/lc/test");
    auto connection = std::make_unique<Connection>(database.get());
    // Execute a simple query.
    auto result = connection->query("MATCH p = (a:Entity)-[e:Connection*8..9]->(b:Entity) WHERE (a.id = " 
    "'openx|bigquery_prod|COLUMN|ox-data-prod.events.transactions_prompt_v3.arc.x_mkt_excluded' OR a.id = "
    "'openx|bigquery_prod|TABLE|ox-data-prod.events.transactions_prompt_v3') WITH a.id AS a_id, p as path RETURN path ");
    // Print query result.
    std::cout << result->toString();
}
```

In the output, I can see something like:
`id: ?1EntitydatascXopenk`?COLUMNet_54BIGQUEbigq?`??9Entityb078aewopen?`?` and 
`id: openx|bigquerybigq?`?`
in the shell, which are invalid strings similar to those that cannot be handled by Python.

Notably, when the query is simply `MATCH (a)-[e]->(b) RETURN *;` Python can finish execution without error. So I suspect that the issue might be due to memory corruption in multi-hop query.

**Comment by andyfengHKU** [comment]
Close because this is no longer reproducible
