### ISSUE TITLE
Add Path UDF Example To Documentation

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#2322]
Manipulating path is a non-trivial task. Many functionalities are ad-hoc and cannot be provided through path function. Since we now have UDF, it would be helpful to provide a path UDF example so that users can write their own logic as needed.

**Comment by semihsalihoglu-uw** [comment]
I suggest using an example database like below. Suppose the blue nodes are of TypeA and the white ones are of TypeB.  I would give 2 examples.

Example 1: Super Nodes
For the first example, I suggest we demonstrate a UDF that "merges any sequence of consecutive Type B nodes  on a path as a single super TypeB node that sums some property on those merged Type B nodes". Suppose all edges are of type `R`. I suggest asking a query like this:
```
MATCH p = (s:A)-[e:R*]->(d:A)
WHERE s.id = a1 AND d.id =a3
RETURN convertToSuperNodes(p) as newP
```

In the below example there are 4 paths between `a1` and `b3`. The path that always follows the upper edges would be transformed and returned as:

- (a1)->(B1: {val: 15})->(a2)->(b3: {val: 1})->(a3)
Instead the path that always follows the bottom edges would be returned as: 
- (a1)->(B1: {val: 120})->(a2)->(B2: {val: 3})->(a3)

I am using capital B to identify super nodes but I am not sure how to return these merged nodes. Maybe return them as a different node type altogether with made up IDs because I do not think it would be easy to guarantee that if the UDF runs in parallel that the IDs will be unique.

Example 1: Super Relationships
We should also give a second example that would completely remove the super nodes and directly connect the A nodes with each other through "super relationships" by merging some property of the merged edges. Consider the edge weights in the example from 1 to 11. We can do an example that removes all edges and B nodes in the paths between a1 and a4 and directly connect the A nodes. So consider now the query:
```
MATCH p = (s:A)-[e:R*]->(d:A)
WHERE s.id = a1 AND d.id =a4
RETURN convertToSuperEdges(p) as newP
```
The top path from a1 and a4 would be returned as:
- (a1)-[SR: {w: 6}]->(a2)-[SR: {w: 9}]->(a3)-[SR: {w: 6}]->(a4)
The bottom path would be returned as:
- (a1)-[SR: {w: 27}]->(a2)-[SR: {w: 26}]->(a3)-[SR: {w: 6}]->(a4)
Note that I have also converted the last direct edge between a3 and a4 into a super relationship. We might have an example that does not do and returns the original relationship for that case. Either is fine I think.

**Comment by andyfengHKU** [comment]
The original rationale was to allow user implement algorithm through UDF. Since now we are working on an algorithm package, I'm closing this.
