### ISSUE TITLE
Deleted DiskArrayUpdateTest

### ISSUE THREAD

**Issue by Riolku** [kuzudb/kuzu#2342]
#2340 deletes disk_array_update_test. We should decide if we need this, and if so, we should make the test work with our new codebase.

This issue also serves as a marker for if we want to restore the file.

**Comment by semihsalihoglu-uw** [comment]
To give a bit more context: Back in the day, I had written a set of tests to test DiskArray's core functions, such as push_back and read, with the aim of testing that we can update DiskArrays transactionally. My solution to do test these core functionalities were to perform a set of updates to ListHeaders, which used to store the CSR headers of lists, and test that they happened transactionally. So ListHeaders were a wrapper to test the basic DiskArray functionality. As I understand, ListHeaders have since then been removed as a class. So if we want to keep the same tests, we need a different mechanism now.

**Comment by ray6080** [comment]
I don't think we need to maintain these tests that are specific on disk array updates. Currently, columns are using disk arrays to store ColumnChunkMetadata, and hash indexes are also using disk arrays to store slots. Both of these should be good enough to cover the tests on disk array updates.

**Comment by semihsalihoglu-uw** [comment]
OK, then I'm closing this issue.
