### ISSUE TITLE
Rust test `db_struct` fails on RHEL-9 platform with GCC toolchain

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#2351]
### Output
```
failures:

---- value::tests::db_struct stdout ----
Error: Query execution failed: Runtime exception: NestedVal::getChildPointer index out of bound.


failures:
    value::tests::db_struct

test result: FAILED. 111 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.55s

error: test failed, to rerun pass `--lib`
```

### CI log:
https://github.com/kuzudb/kuzu/actions/runs/6771138806/job/18400936125

### Platform:
The CI uses `rockylinux:9` container, but this issue is also reproducible on a CentOS Stream 9 physical server (uw5) with the following toolchain:

- GCC 11.4.1 20230605
- rustc 1.73.0 (cc66ad468 2023-10-03)

Note that all tests would pass by overriding the compiler to LLVM 16:
```
CC=clang CXX=clang++ CARGO_BUILD_JOBS=$(nproc) cargo test --release --features arrow -- --test-threads=1
```

**Comment by benjaminwinger** [comment]
I took a quick look at this. It's not clear why it's failing since the code should only be accessing fields within the range of the result of `NestedVal::getChildrenSize`. To try and determine if it's an issue with the rust code or a more general one, I added a C++ test which does the same as the failing rust test as there was not otherwise any C++ API test testing passing a struct as a parameter (https://github.com/kuzudb/kuzu/commit/06ee149009bf27e0c25c1aafbcf38458a1112674).
The test works as expected locally (including with ASAN), however the Multiplatform build & test pipeline is failing in the setup stage (yum issue I'm not familiar with) so I can't test this against the same system which causes the rust test to fail at the moment.
