### ISSUE TITLE
Node is created with SERIAL property missing under certain circumstances

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2402]
After executing the following
```
CREATE NODE TABLE A(pk1 SERIAL, PRIMARY KEY(pk1));
CREATE NODE TABLE B(pk2 SERIAL, PRIMARY KEY(pk2));
CREATE NODE TABLE C(pk3 SERIAL, PRIMARY KEY(pk3));
CREATE (:A);
CREATE (:B);
```
Executing the query
```
MATCH (n) RETURN n;
```
Gives the following output:
```
---------------------------------
| n                             |
---------------------------------
| {_ID: 0:0, _LABEL: A, pk1: 0} |
---------------------------------
| {_ID: 1:0, _LABEL: B}         |
---------------------------------
```
Where `pk2: 0` is missing from the second row.
The issue does not occur without `CREATE NODE TABLE C`.

**Comment by benjaminwinger** [comment]
As far as I can tell, the issue is that we're re-using the ValueVectors that store the scan results, however, serial columns don't have a null column and aren't updating the null data in the result vectors (there's an assert that the result vector is not null, which fails in this example if runtime checks are enabled).

Prior to scanning the B column, something, presumably related to the empty `C` table, is scanning a column with an id of `INVALID_COLUMN_ID`, which sets everything in the vector to null ([here](https://github.com/kuzudb/kuzu/blob/15ac0e3a89db9c3b7e07ca62532bb5b4bb621176/src/storage/store/node_table_data.cpp#L38)), despite there being no actual null values being scanned, but it presumably could also occur if a column containing null values was scanned first.
