### ISSUE TITLE
Configure URL redirection for popular Kuzu links

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2605]
If you search for Kuzu, there currently are some more popular links pointing to blog entries under old URL:
- https://news.ycombinator.com/item?id=33609082
- https://news.ycombinator.com/item?id=34959895
- https://news.ycombinator.com/item?id=34358912
- https://news.ycombinator.com/from?site=kuzudb.com

which point to `https://kuzudb.com/blog/xxx.html`.

For example https://kuzudb.com/blog/what-every-gdbms-should-do-and-vision.html 
, but current URL is https://kuzudb.com/docusaurus/blog/what-every-gdbms-should-do-and-vision/.

To keep links online and spread the word for Kuzu, I'd suggest to redirect URLs `https://kuzudb.com/docusaurus/blog` to `https://kuzudb.com/blog` (shorter) and also forward/strip off trailing `*.html`.

Edit: Also `https://kuzudb.com/docs/blog` -> `https://kuzudb.com/blog`

**Comment by semihsalihoglu-uw** [comment]
Thanks @sapalli2989. This is a good advice. We should do this.

**Comment by mewim** [comment]
Prior to deployment of the new blog website I have set up a redirection to make sure that the old links still work (https://github.com/kuzudb/kuzudb.github.io/tree/main/blog). However, currently we cannot get rid of the `docusaurus` prefix easily as the website is actually two sites glued together: the front page is raw HTML and the docs and blogs are a separate React.js website managed by docusaurus. We need to redesign the front page with React.js and migrate everything to docusaurus in order to get rid of the prefix.

**Comment by semihsalihoglu-uw** [comment]
I think the effort is a bit too much to do this soon, I'm closing this issue for now but thanks a lot for pointing this out.
