### ISSUE TITLE
Per-index Memfile Locking Contention

### ISSUE THREAD

**Issue by Riolku** [kuzudb/kuzu#2626]
After #2615, we lock a shared in-memory file for string keys in the hash index. Though this works, it is likely (?) a point of contention when strings are long. As mentioned in [this comment](https://github.com/kuzudb/kuzu/pull/2615#discussion_r1435770346), one solution is to let each thread grab a page at a time.

**Comment by benjaminwinger** [comment]
For the InMemFile used by the builder, reading concurrently isn't really an issue anyway, so I don't think grabbing a page at a time (if I understand what that means correctly) is really the optimal solution.

There are some ways we can avoid/reduce locking when reading ([see here](https://github.com/kuzudb/kuzu/pull/2776#issuecomment-1930842530)), but I'm thinking that a better way would be to have an overflow file for each concurrent index so that we can do parallel writes. They could even share the same file handle (meaning there would still be some locking for assigning new page numbers, but that's the same as for the main index file), as long as the page index of the next page is stored at the end of each page so that strings broken up between multiple pages can still be pieced back together.
There will of course be a similar amount of unnecessary size overhead with small databases as with the main index file.

Or we could stick with the current serial append (ideally without locks for reads), and limit locking to updating the `nextPosToAppend` cursor before writing the string (adding new pages at that point) so that the locks are held for as little time as necessary and the actual writes can be done as parallel as possible.

**Comment by ray6080** [comment]
The latter one seems easier and I think we should give a try on that first?

**Comment by benjaminwinger** [comment]
I just realised that my test in #2776 wasn't even using long strings, so our performance is currently really bad even when we don't actually need the memfile (part of the issue is that we're always locking when writing/comparing short strings as well as long strings). The same test with strings of a length of ~29 (random integers with a 21 character string appended) took 239s, which is 108x slower than integers, and 7x slower than short strings.

Note that without reserving strings, the performance on master has changed to 2.2s for integers and 30s for short strings (the extra read/write when rehashing for short strings is evidently more costly than the cost of reading the number of rows ahead of time).

I did a quick test of parallel writes (without actually making sure that the subsequent strings are readable if they cross page boundaries by writing the next page at the end of the file since that's really the only complicated part) and it improved the short string copy to ~6s and the long string copy to ~14s.

Locking only when pre-allocating space to write strings, the short string performance improved to about 6s again (as expected, since we no longer lock for short strings) but the long string test took 159s, which is better than it currently is, but still far worse than with parallel writes.
