### ISSUE TITLE
Kuzu can not return the results for queries containing non-bounded path variable

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#2640]
Hello here~
I run the following simple query in Kuzu with a small graph (*i.e.,* 5 nodes and 10 edges), but can not obtain the result for a long time.
```cypher
MATCH (n1)-[*]->(n2) RETURN COUNT(*)
```
I guess the root cause is the inner bound of Kuzu for the path variable somehow not being successfully triggered.

The graph data for reproducing the case is attached.

[Graph Data](https://github.com/kuzudb/kuzu/files/13873815/gaph.zip)

Your effort in investigating and confirming this case will be highly appreciated.

Best regards,
Qiuyang

**Comment by andyfengHKU** [comment]
Hi @joyemang33, thanks for reporting.

Looks like the hanging is due to the explosion of large query result because we allow arbitrary repeated node and edges during traversal, i.e. we use `WALK` semantic instead of `TRAIL` or `ACYCLIC`.

On the other hand, we do believe a `TRAIL` or `ACYCLIC` semantic makes more sense in practice and we will try to implement these semantics as well.

Meanwhile, if you encounter a similar hanging query. You can use `CALL timeout=xxx` (ms) to early terminate.

**Comment by andyfengHKU** [comment]
The default semantic is still `WALK`. Once switch to other semantic, e.g. `TRAIL`. This is properly handled.
