### ISSUE TITLE
Parse all paths between two nodes

### ISSUE THREAD

**Issue by dkioroglou** [kuzudb/kuzu#2665]
Hello,

I have a question on how to get all possible paths between two nodes.
I have the following graph:
```
      nB - nC
    /         \
  nA           nF
    \         /
      nG - nE
```

I want to get all possible paths between nodes `nA` and `nC` which are:

* **path 1**: `nA - nB - nC`
* **path 2**: `nA - nG - nE - nF - nC`

Based on the documentation, I found how to get the shortest path (**path 1**):

```
MATCH p = (s:Vertex {name:"nA"})-[r:Relation * ALL SHORTEST]-(t:Vertex {name: "nC"})
RETURN properties(nodes(p), 'name') AS name, properties(rels(p), 'info') AS info;
```

I thought that by removing `ALL SHORTEST` I would get all possible paths (**path 1** and **path 2**):
```
MATCH p = (s:Vertex {name:"nA"})-[r:Relation *]-(t:Vertex {name: "nC"})
RETURN properties(nodes(p), 'name') AS name, properties(rels(p), 'info') AS info;
```
but this query raises the exception:
```
RuntimeError: Buffer manager exception: Failed to claim a frame.
```
You have an example in the documentation on how to parse all direct and indirect paths, but I find that example too complicated. 
Could you provide some guidelines on how to parse all paths between nodes `nA` and `nC` in this simple example?

Thank you in advance.

**Comment by semihsalihoglu-uw** [comment]
Hi @dkioroglou,

First, please join our Discord server: https://discord.gg/cnxYf3Yc. We're very active there to respond to questions (we just moved there from Slack so the amount of activity may look little for now but will pick up).

The query you're asking finds all "undirected paths" up to a default max length of 30 but there are exponentially many of them. I'm putting "undirected paths" in quotes because every path in Kuzu is directed, since every edge is directed. Undirected relationship patterns are simply syntactic sugars to ask for "unions of join queries", i.e., where each matched edge can take arbitrary direction. 

In your example graph you have drawn the edges in your original graph as undirected. I am not sure how you modeled the edges, regardless, let me just assume that you have 6 edges and that they go from left to right (so nA -> nB, nB->nC, nC->nF, etc.). Even in this case for your "undirected paths" query, there are many matches. For example:

nA -> nB->nC
nA -> nB->nC<-nB->nC
nA -> nB->nC<-nB->nC<-nB->nC
...

So it's not a very good idea to ask for undirected patterns (at least without limiting the lengths of the paths to something small).

You can make your edges "undirected" meaning you can double the number of edges and insert 12 edges into your database. So (nA -> nB, nB->nA, nB->nC, nC->nB, nC->nF, nF->nC, etc...). Then you can ask a directed version of you question.

```
MATCH p = (s:Vertex {name:"nA"})-[r:Relation *]->(t:Vertex {name: "nC"})
RETURN properties(nodes(p), 'name') AS name, properties(rels(p), 'info') AS info;
```
This should now finish but even this is not guaranteed to find exactly what you want. Because this will return the following:

nA -> nB->nC
nA -> nG->nE->nF->nC
nA -> nB->nC->nF->nE->nG->nA->nB->nC

So some edges may be repeated. There is a function called `[is_trail(p)](https://kuzudb.com/docusaurus/cypher/expressions/path_functions#is_trail)` you can use to filter paths that repeat edges. This has to be used in the `WHERE` clause as follows: 

```
MATCH p = (s:Vertex {name:"nA"})-[r:Relation *]->(t:Vertex {name: "nC"})
WHERE is_trail(p)
RETURN properties(nodes(p), 'name') AS name, properties(rels(p), 'info') AS info;
```

Let us know if this works.

**Comment by semihsalihoglu-uw** [comment]
@dkioroglou: My previous answer was not very accurate so I updated it. See my updated answer ^.

**Comment by dkioroglou** [comment]
Hello,

Thank you for your quick response. Apologies, I wasn't aware of the Discord server... definetely will check it out next time.
It's true that the example I gave was too vague, so I will include an image.
So, I have the following network:
![fig1](https://github.com/kuzudb/kuzu/assets/21988818/c96af418-16af-4ddc-98d4-9e35be230ec5)

What I'm looking for is to get all possible paths between nodes `geneA` and `geneC`. I was going for undirected paths in the query because the direction in the node `protein` changes. To my mind, I thought that the `is_trail` restriction is implied when specifying that the paths should be between two given nodes and paths like the one between `geneA` and `geneG` will be excluded.

So, your suggestion `WHERE is_trail(p)` works great. 
```
MATCH p=(s:Vertex {name: "geneA"})-[r:Relation *1..5]-(t:Vertex {name: "geneC"})
WHERE is_trail(p)
RETURN properties(nodes(p), 'name') AS name, properties(rels(p), 'info') AS info, properties(rels(p), 'source') AS source;
```

I get the expected paths between `geneA` and `geneC` and exclude the path between `geneA` and `geneG`.
![fig2](https://github.com/kuzudb/kuzu/assets/21988818/e76ed7b8-8987-4240-b139-82f1d9998178)
