### ISSUE TITLE
Inconsistent behaviour when inserting/copying a list of string.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2755]
I noticed an inconsistent behaviour when copying from/inserting the same list of string to organisation table:
1. Using copy from statement:
```
csv file:
1,ABFsUni,325,3.7,-2,10 years 5 months 13 hours 24 us,3 years 5 days,1,"{revenue: 138, location: ['toronto', 'montr,eal'], stock: {price: [96, 56], volume: 1000}}",3.12
```

  The `location` list with two strings will be interpreted as (both with a single quote): 
  a. ('toronto') 
  b. ( 'montr,eal') (with a leading space);

2. Using Insert statement:
CREATE (:organisation {ID: 25, state: {'revenue': 138, 'location': ['toronto',  'montr,eal'], 'stock': {'price': [96, 56], 'volume': 1000}}})
  The `location` list with two strings will be interpreted as (without a single quote): 
  a. (toronto) 
  b. (montr,eal) (without a leading space);

**Comment by manh9203** [comment]
I just tested and the issues stem from our string-to-varlist parser. Leading spaces can be fixed by trimming before casting. 
Since single quotes are unnecessary when casting a string to a string list, they are currently parsed as part of the string. Many of our csv files in the dataset also don't have the single quotes, i.e: ```"[toronto, montreal]"``` instead of ```['toronto', 'montreal']```. Which format should we support?
