### ISSUE TITLE
Buffer manager exception: Failed to claim a frame: Python API: Bulk Load kuzu==0.0.12 v  kuzu==0.2.0 

### ISSUE THREAD

**Issue by saschamcdonald** [kuzudb/kuzu#2863]
Python API:

Executed on a Mac local client: 2.6 GHz 6-Core Intel Core i7. AMD Radeon Pro 5300M 4 GB. Intel UHD Graphics 630 1536 MB. Memory 32 GB 2667 MHz DDR4

Scenario:
A parquet snappy compressed file to bulk load a relationship table, file size: 1.97 GB from disk:
Version of Kuzu:
kuzu==0.0.12
Result:
Loads successfully

Version of Kuzu:
kuzu==0.2.0
Result: ERROR:
Buffer manager exception: Failed to claim a frame.

**Comment by ray6080** [comment]
Hi @saschamcdonald , thanks for reporting this! We've made significant changes to the rel storage since v0.1.0, and that should be why the behaviour is inconsistent between these two versions, though the exception is not expected. We'd love to look into the exception and fix it. Is it possible for you to share the parquet file with us?

**Comment by ray6080** [comment]
Hi @saschamcdonald , thanks for the info. Is it possible to share the rel table schema and some statistical information of the dataset, like number of nodes and number of rels and also some degree distribution info? We can try to reproduce this locally on our side.

> I'll try and create test data over the next couple of weeks to offer a repeatable test data set for the team.

That would be much appreciated!

> In the interim is there a debug level I can set to capture more info for the team?

Unfortunately, we currently don't have a way to collect more debugging info without compiling from source and running inside a debugger.

**Comment by ray6080** [comment]
hi @saschamcdonald thanks for sharing this. will take a look into it.

**Comment by semihsalihoglu-uw** [comment]
@saschamcdonald: This error means that the buffer manager is running out of memory. A couple of questions:

- How much RAM do you have on the machine? You might need to try to on a larger machine.
- How many nodes do your node tables have?
- If you can share the database somehow we can test to see how much memory we require for this now. If the test databases was generated from your generator, let us know how we can generate a similar database.

**Comment by prrao87** [comment]
Hi @saschamcdonald we'll take a look at the artificial dataset repo that you created, it shouldn't be hard to reproduce. Will get back to you on this.

**Comment by prrao87** [comment]
Got it, will keep you posted.

**Comment by prrao87** [comment]
@saschamcdonald We've narrowed it down to the partitioning changes introduced in 0.1.0, explaining why it worked up to Kùzu 0.0.12. We'll need to run some profiling to further isolate the issue.

For now, since this is a showstopper, could you run your workflow with the latest release that works (0.0.12)? I was able to successfully load it up until that version. We'll look into this more and update you when we have a fix. Thanks!

**Comment by prrao87** [comment]
Yup, we saw the same on our end too. As I mentioned, @ray6080 will get back to you on our next steps for the latest version of Kùzu, but you at least have a version that works.

**Comment by ray6080** [comment]
Hi @saschamcdonald, we've got the root cause inside our partitioner. briefly, the problem is due to that we unnecessarily allocated large memory blocks for strings, and that makes BM go out of memory when we have a large num of rel tuples with a few string properties. Will open an issue on this with a solution and let u know once we fixed it.
