### ISSUE TITLE
Enable multiple node types for single relationship type table 

### ISSUE THREAD

**Issue by d33bs** [kuzudb/kuzu#2866]
Excited about the possibilities of Kuzu, thanks for your great work on this project! This issue may overlap with #1644 (perhaps the "Data Manipulation" section?), but it felt important enough to be specific here.

I noticed that each REL table in Kuzu may only contain one node type for the FROM and TO specification ([docs](https://kuzudb.com/docusaurus/cypher/data-definition/create-table#create-rel-table)). This may be limiting in scenarios where a graph dataset includes relationships that involve multiple node types. I wanted to raise this issue to help explore and understand the capabilities within Kuzu to perhaps eventually use multiple node types in the FROM or TO specification for REL tables. Please don't hesitate to mention whether this is considered "out of scope" for the Kuzu roadmap more broadly.

I'm also interested in potential workarounds to this in the meantime, understanding it could take time for this feature to arrive if it's intended to be developed. Two that come to mind are:

- Generalize all NODE types to a single table of type / name `nodes` (enabling relationship tables to reference all `nodes` no matter their name).
- Create specific REL tables for each kind of relationship by distinct FROM, TO node pairs (specifying this within the REL table name somehow, i.e. `rel_nodeone_to_nodetwo`).

Both of these may come with ramifications that over-loosen or constrain the data, and I imagine there could be a performance element to these. Appreciate any input you may have on this topic! Thanks again.

**Comment by ray6080** [comment]
Hi @d33bs , this is a good topic. I've got one input here: One work around we have right now is [REL TABLE GROUP](https://kuzudb.com/docusaurus/cypher/data-definition/create-table#create-rel-table-group), which can life some limitation of "each REL table in Kuzu may only contain one node type for the FROM and TO specification".

**Comment by andyfengHKU** [comment]
Hi @d33bs, thanks for trying us out!

Indeed for some graph databases, a relationship (REL table) can be defined over multiple node tables, e.g. the following is doable in Neo4j
```
CREATE (:A)-[e:R]->(:B);
CREATE (:C)-[e:R]->(:D);
MATCH ()-[e:R]->() RETURN e;
```
Here we define a relationship R over FROM A TO B and FROM C TO D. The above statements can also be rewritten as with multi-label query which is exactly the same as your second workaround suggestion.
```
CREATE (:A)-[e:R_AB]->(:B);
CREATE (:C)-[e:R_CD]->(:D);
MATCH ()-[e:R_AB|:R_CD]->() RETURN e;
```

Back in the day, we thought since there was a workaround, we could just go for a simpler modelling which also benefits bulk-loading performance, data compression and other system level optimizations. So we chose to constraint REL table to be defined over one pair of FROM TO node tables.

Though slowly we indeed receive feedbacks about the limitation of this constraint in practice. So we introduced [REL GROUP](https://kuzudb.com/docusaurus/cypher/data-definition/create-table#create-rel-table-group) as an experimental feature where you can define a rel group and use it as a union of multiple relationship tables during querying. 
```
CREATE REL TABLE GROUP R (FROM A TO B, FROM C TO D);
MATCH ()-[e:R]->() RETURN e;
```
This feature is quite experimental so it comes with many limitations, e.g. you can not bulk-load into a rel group. Any feedback over this feature is highly appreciated.

As for the workarounds
> Generalize all NODE types to a single table of type

I don't recommend this one because it will definitely hurt performance because a node table scan will be a lot more costly.

> Create specific REL tables for each kind of relationship by distinct FROM, TO node pairs

This idea aligns with our initial thoughts and I believe it will work fine.

**Comment by d33bs** [comment]
Thank you so much @ray6080 and @andyfengHKU ! I'll give REL GROUP's a try and follow up with any feedback.

**Comment by semihsalihoglu-uw** [comment]
I'm closing this issue for now assuming RelGroup will do for now. Please re-open if your feedback has a request for a feature we should consider.
