### ISSUE TITLE
Build CLI binary as executable prior to zip/release

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#2880]
The current CLI downloaded via the URL (for example, [this one](https://github.com/kuzudb/kuzu/releases/download/v0.2.0/kuzu_cli-linux-x86_64.zip)), when unzipped just provides a file. The user has to manually convert the file to an executable on Linux/MacOS by typing `chmod +x kuzu` to allow it to be executed.

Is there something that could be done during the build process that allows us to unzip the downloaded file directly as an executable?

**Comment by benjaminwinger** [comment]
We're using the upload-artifact action, which [according to its documentation](https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss) does not preserve file permissions (not all zip tools handle permissions, as permissions were an extension of the format as far as I'm aware). There is an [open issue](https://github.com/actions/upload-artifact/issues/38).

I think all that should be necessary is to manually create the zip archive with a tool that supports permissions, and upload that.

**Comment by mewim** [comment]
Instead of creating zip file, let's just switch to `tar.gz`, which should preserve file permissions robustly. However, as per https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives:

> When an Artifact is uploaded, all the files are assembled into an immutable Zip archive. There is currently no way to download artifacts in a format other than a Zip or to download individual artifact contents.

There are also several related issues: https://github.com/actions/upload-artifact/issues/109 and https://github.com/actions/upload-artifact/issues/39.

So this means that the build pipeline will create a `tar.gz`, but it will be double-zipped by upload-artifact. The person responsible for releasing needs to unzip the artifact and upload the enclosed `tar.gz` file.

**Comment by prrao87** [comment]
Does this work on all OSes without any issues? If so, we should properly document it.

**Comment by mewim** [comment]
> Does this work on all OSes without any issues? If so, we should properly document it.

tar.gz should be supported by macOS and most Linux distros by default. For Windows, we will keep publishing zip. I do not have a Windows machine to test right now, but I think Windows also does not require setting permission for exe files (@acquamarin and @benjaminwinger can comment)?
