### ISSUE TITLE
Missing test coverage for ```scanArrowArray```

### ISSUE THREAD

**Issue by manh9203** [kuzudb/kuzu#3186]
These type combinations in arrow reader (```scanArrowArray```) are missing test coverage:
- ```MonthInterval```
- ```DayTimeInterval```
- ```MonthDayNanoInterval```
- ```BLOBView```
- ```ListView```
- ```DenseUnion```
- ```SparseUnion```
- ```RunEndEncoded```
- ```DictionaryEncoded (int8_t, uint8_t, int16_t, uint16_t, uint32_t, int64_t, uint64_t)```
- ```FixedSizePrimitive (int8_t, uint8_t, int16_t, uint16_t, uint32_t)```
- ```List (int64_t)```
- ```DurationScaledUp (scale factor = 1000)```

**Comment by mxwli** [comment]
Status on tests as of now:
For the interval types and view types, tests are not implemented because either pandas or the pyarrow API hasn't implemented good support for them.
Union testing hasn't been done because Union scanning hasn't been implemented. That part is on its way.
Run end encoding isn't tested because pandas doesn't support run-end encoded arrays IIRC (though this may have changed)
The rest of the templates could use testing for coverage, but I'm not sure if that would be high priority.

**Comment by andyfengHKU** [comment]
This is done.
