### ISSUE TITLE
Optimization: Optimizing the scheduling overhead of the short queries

### ISSUE THREAD

**Issue by ted-wq-x** [kuzudb/kuzu#3695]
### Description

In some short quries,for example, ldbc sf100 database,` match (a:vertex)-[]-(b) where a.__uid='10010832' return count(b);` 
<img width="736" alt="image" src="https://github.com/kuzudb/kuzu/assets/22289061/f51b3581-95e1-44a3-b55b-917353222e61">

ScanMultiRelTable::initLocalStateInternal wasted a lot of time

<img width="450" alt="image" src="https://github.com/kuzudb/kuzu/assets/22289061/6bcfa4eb-6f6f-4b51-8544-e59f4d3663f6">

**Comment by ray6080** [comment]
Hi @ted-wq-x , can u show us the changes on how u get the `InitTime`?

**Comment by ray6080** [comment]
It's mostly due to the initialization of ColumnChunks inside rel table scan states. We pre-reserve column chunks at size of NODE_GROUP_SIZE (default to 64*2048) for both CSR lengths and offsets, which can be aggressive in some cases, especially under multi rel label scans. Will optimize this soon. Thanks for reporting this!

**Comment by ted-wq-x** [comment]
> Hi @ted-wq-x , can u show us the changes on how u get the `InitTime`?
