### ISSUE TITLE
CLI: Provide better error message when trying to open `READ_ONLY` connection when lock file is in use

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3883]
Currently, we provide an error message that's not very helpful when a user tries to open a `READ_ONLY` connection to a database whose lock file is held by another process (e.g., a running Jupyter notebook or Python script).

This is our current CLI error message:
```
❯ kuzu ./db -r
Opened the database at path: ./db in read-only mode.
Enter ":help" for usage hints.
IO exception: Could not set lock on file : ./db/.lock
```
It just says "could not set lock on file", but that's not very helpful. Also, it says "opened the database" despite not doing so and producing an error, which is again, not helpful.

Instead, we could say something along the lines of the following:

```
❯ kuzu ./db -r
Error: unable to open database "./db": IO exception: Could not set lock on file : ./db/.lock
See the docs: https://docs.kuzudb.com/connections/concurrency for more information.
```
At least this would point the user to the actual cause and the docs page that helps them understand more.

Here's how DuckDB does it  -- it specifies the exact process ID that's conflicting and which user on the machine is the owner of that process, not sure if we can do that as well, but that would be great:

```
❯ duckdb ./test.duckdb --readonly
Error: unable to open database "./test.duckdb": IO Error: Could not set lock on file "./test.duckdb": Conflicting lock is held in /Users/prrao/.pyenv/versions/3.12.4/bin/python3.12 (PID 97844) by user prrao. See also https://duckdb.org/docs/connect/concurrency
```

**Comment by prrao87** [comment]
Just an update here: the concurrency docs are now online, so I think we should fix this error message to be more informative and point the user to the docs. Something like this:
```
❯ kuzu ./db -r
Error: unable to open database "./db": IO exception: Could not set lock on file : ./db/.lock
See the docs: https://docs.kuzudb.com/concurrency for more information.
```

**Comment by WWW0030** [comment]
It seems that the code in `shell_runner.cpp` goes through the same if statement regardless of whether it is able to set lock on file. I changed `Opened the database at path: ./db in read-only mode.` to `Opening the database at path: ./db in read-only mode.` because I think that describes the action better. 
Let me know if this is good or should we find a way to separate the error case to go through a different route. I also added a link to concurrency information in case of error. 

Link to PR: https://github.com/kuzudb/kuzu/pull/4248
