### ISSUE TITLE
Suggestions for improving kuzu documentation

### ISSUE THREAD

**Issue by jshengst** [kuzudb/kuzu#3921]
### Description

I am a novice, and I encountered some difficulties that are not mentioned in the documentation when I compiled kuzu in VS. Here are my solutions and new doubts:

1. The C++ version needs to be set to C++20

2. Turn on "/EHsc"

3. Turn off SDL checking

4. Only x64 release version can be compiled

If any of the above conditions are not met, an uncompilable error will be generated. But it is not perfect, and some warnings will still be generated. Fortunately, the demo works normally.

I hope these experiences can help others, and I also want to know if there is a way to solve these warnings about type conversion loss information?

**Comment by prrao87** [comment]
Hi @jshengst, thanks for the feedback! Could you let us know where in the docs you looked, and which pages didn't answer your questions? It would help us focus on improving the right section of the docs.

**Comment by jshengst** [comment]
https://docs.kuzudb.com/get-started/#quick-start
In the C++ chapter here, there is only a very simple one-line command line introduction in the window platform compilation part. If you use VS, you will encounter many problems.

If the first demo is difficult to use, it will hinder many users who want to try out how useful Kuzu is. :)

**Comment by mewim** [comment]
Hi @jshengst,

Thanks for your suggestions. Regarding the build process, we recommand using msvc as a compiler, but invoking the build process through CMake + Ninja generator as outlined in https://docs.kuzudb.com/developer-guide/#windows-10. If you follow these steps, the build should success without requiring additional flags/settings. We also test using MSVC as a generator in our CI (e.g. https://github.com/kuzudb/kuzu/actions/runs/10071552581/job/27841948838). If you use CMake to generate an MSVC project first instead of directly open the repository, it should also work without additional settings required.

Regarding the warnings, they are not quite solvable by just modifying compiler settings. Since Kùzu was originally developed for POSIX (Linux / macOS) and later ported to Windows, many of the types are different due to platform/compiler differences. These need to be reviewed and fixed manually.

Regarding the docs, we provide support for one toolchain per platform. While you may prefer to use Visual Studio, it is not possible for us to provide instructions for all IDEs / toolchains. So outside of the suggested setup, it would be up to the user to figure out how to properly set it up. Additionally, for regular users, we suggest using the pre-compiled binaries (https://kuzudb.com/#download) instead of compiling from source.

**Comment by mewim** [comment]
> @mewim Hi, thanks for the reply. I compile using .hpp + .lib.
> 
> I use Visual studio because another library I'm using has not been ported to CMAKE yet, and I have to make sure kuzu works in VS.
> 
> It took some time to figure it out in the end, so wanted to see if it helps others.

I see. So the comment is not regarding how to build kuzu, but how to integrate the pre-compiled library into an exisitng Visual Studio project. Does the command of directly invoking `cl /std:c++20 /EHsc main.cpp kuzu_shared.lib` work for you?
