### ISSUE TITLE
Bug: SelectionVector bug in windows

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#4549]
### Kùzu version

master

### What operating system are you using?

MAC M1

### What happened?

1. `isContinuous` triggers an assertion failure(cant dereference out of range vector iterator) on windows debug build: 
```
bool isContinuous() const {
        return selectedPositions >= &*INCREMENTAL_SELECTED_POS.begin() &&
               selectedPositions <= &*INCREMENTAL_SELECTED_POS.end();
    }
```
According to this post:
[cant dereference out of range vector iterator](https://stackoverflow.com/questions/57928328/cant-dereference-out-of-range-vector-iterator-whats-the-problem)
Looks like `&INCREMENTAL_SELECTED_POS.end()` is unsafe in windows.

2. `isUnfiltered` is not safe in windows:
```
    bool isUnfiltered() const { return selectedPositions == INCREMENTAL_SELECTED_POS.data(); }
```
We use pointer based arithmetic in windows to determine a vector is filtered or not, where `INCREMENTAL_SELECTED_POS ` is a static field in selectionVector.
However, the initialization of static fields behaves differently than linux/mac.
```
 (lldb) p selVector.INCREMENTAL_SELECTED_POS.data()
(const unsigned long long *) $49 = 0x00007ffff97b6290 {libfts.kuzu_extension!std::array<unsigned __int64,2048> const kuzu::common::SelectionVector::INCREMENTAL_SELECTED_POS} {0}
(lldb) p selVector.selectedPositions
(unsigned long long *const) $50 = 0x00007ff74d420080 {e2e_test.exe!std::array<unsigned __int64,2048> const kuzu::common::SelectionVector::INCREMENTAL_SELECTED_POS} {0}
```
I suggest we use an enum to indicate whether it is filtered or not.

**Comment by benjaminwinger** [comment]
> [cant dereference out of range vector iterator](https://stackoverflow.com/questions/57928328/cant-dereference-out-of-range-vector-iterator-whats-the-problem)
Looks like &INCREMENTAL_SELECTED_POS.end() is unsafe in windows.

`&INCREMENTAL_SELECTED_POS.end()` isn't dereferencing the end pointer though; it's just getting the address, so I don't think that should be a problem (I think the array iterator should be directly convertible to an address without dereferencing since it's a [contiguous_iterator](https://en.cppreference.com/w/cpp/iterator/contiguous_iterator) which is required to have an implementation of `std::to_address`). However the addresses not matching with the extensions is certainly an issue.

**Comment by benjaminwinger** [comment]
Oh, indeed.
I guess using `std::to_address` directly would fix that, but it's probably better to get rid of it entirely to fix the other issue.

**Comment by LowLevelMahn** [comment]
> &INCREMENTAL_SELECTED_POS.end() isn't dereferencing the end pointer though;

but its `&*INCREMENTAL_SELECTED_POS.end()` with the `*` so it is actually dereferencing
the Linux/Windows difference is that the Microsoft STL is per default in DEBUG mode when building Debug
for the gcc/llvm STL its only active when using _GLIBCXX_DEBUG (https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html) - then it should assert the same

its undefined behavior and should be fixed because _GLIBCXX_DEBUG will be active per default with gcc 15, see https://gcc.gnu.org/gcc-15/changes.html

> Debug assertions are now enabled by default for unoptimized builds. Use -D_GLIBCXX_NO_ASSERTIONS to override this.
