### ISSUE TITLE
Question: why is the rust build in the Makefile using the MSVC "Debug" Runtime?

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#4553]
0.7.0

in Makefile

```
rust:
ifeq ($(OS),Windows_NT)
	set CFLAGS=/MDd
```

`/MDd` means using Debugging-Runtime as DLL (that means the Runtime is doing the typical more deep testing like Debug-Heap etc. )

https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170

Debug builds should(could) use `/MDd`
but Release builds should use `/MD` - without the `d`

Microsoft MSVC behavior is different to Linux here because they provide Debug and Release Versions of Runtime - which are different in speed and active testing (same like with STL - which does in Debug builds also more testing at runtime)

also is the Debug-Runtime only installed when VStudio is also installed

**Comment by benjaminwinger** [comment]
I think that code was missed in #3226.

That target is only currently being used by the macos build pipeline in CI (everywhere else the build code has been inlined to add flags like `--locked`, which the macos build pipeline presumably would also benefit from). I think we either should get rid of it, or find a way to use it in CI so that it's actually tested.
